### ISSUE TITLE
Générer un tracker

### ISSUE THREAD

**Issue by antbou** [antbou/mailtracker#11]
En tant que membre
Je souhaite pouvoir générer un tracker afin d'avoir une idée du nombre de fois que mon email a été ouvert.

- [x] la barre de navigation contient un bouton "Créer un tracker"
- [x] Lorsque je clique sur le bouton, je suis rediriger sur la page de création de l'email
- [x] Sur la page de création du tracker, je peux rensigner un titre ainsi qu'une adresse email
- [x] Lorsque je n'entre aucune données dans les champs, des messages d'erreurs s'affiches
